### ISSUE TITLE
Crash on logging out when background refresh is ongoing

### ISSUE THREAD

**Issue by vickychijwani** [vickychijwani/quill#56]
This occurs because we're holding onto a `RealmObject` (`mAuthToken`) after the Realm has been deleted (upon logout). Might be reproducible with the following steps:

1. Swipe-to-refresh on post list
2. Logout before refresh completes (actually need to logout even before request is sent?)

Possible fixes:

- Cancel all in-flight requests (or wait until they complete), release all `RealmObject` references (like `mAuthToken`), then logout, or,
- Simply make a copy of `mAuthToken` so it's not connected to Realm (but what about in-flight requests that may be holding references to `RealmObjects`? This doesn't seem like a good idea anymore.)

Cancellation is not directly supported by Retrofit, but can be hacked together:

- By [shutting down the ExecutorService itself](http://stackoverflow.com/a/22053101/504611), or,
- By [creating a Callback delegate that makes `success` a no-op if `CallbackDelegate.cancel()` is called](http://stackoverflow.com/a/23271559/504611).

Stacktrace from [Crashlytics](https://www.crashlytics.com/individual16/android/apps/me.vickychijwani.spectre/issues/555524f4f505b5ccf0d3affc):

```
java.lang.RuntimeException: Could not dispatch event: class me.vickychijwani.spectre.event.LoadUserEvent to handler [EventHandler public void me.vickychijwani.spectre.network.NetworkService.onLoadUserEvent(me.vickychijwani.spectre.event.LoadUserEvent)]: This Realm instance has already been closed, making it unusable.
       at com.squareup.otto.Bus.throwRuntimeException(Bus.java:458)
       at com.squareup.otto.Bus.dispatch(Bus.java:388)
       at com.squareup.otto.Bus.dispatchQueuedEvents(Bus.java:369)
       at com.squareup.otto.Bus.post(Bus.java:338)
       at me.vickychijwani.spectre.view.PostListActivity.refreshData(PostListActivity.java:229)
       at me.vickychijwani.spectre.view.PostListActivity.access$lambda$2(PostListActivity.java)
       at me.vickychijwani.spectre.view.PostListActivity$$Lambda$3.run()
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:135)
       at android.app.ActivityThread.main(ActivityThread.java:5254)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
Caused by: java.lang.IllegalStateException: This Realm instance has already been closed, making it unusable.
       at io.realm.Realm.checkIfValid(Realm.java:189)
       at io.realm.AuthTokenRealmProxy.getCreatedAt(AuthTokenRealmProxy.java:97)
       at me.vickychijwani.spectre.network.NetworkService.hasAccessTokenExpired(NetworkService.java:517)
       at me.vickychijwani.spectre.network.NetworkService.validateAccessToken(NetworkService.java:435)
       at me.vickychijwani.spectre.network.NetworkService.onLoadUserEvent(NetworkService.java:184)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.squareup.otto.EventHandler.handleEvent(EventHandler.java:89)
       at com.squareup.otto.Bus.dispatch(Bus.java:386)
       at com.squareup.otto.Bus.dispatchQueuedEvents(Bus.java:369)
       at com.squareup.otto.Bus.post(Bus.java:338)
       at me.vickychijwani.spectre.view.PostListActivity.refreshData(PostListActivity.java:229)
       at me.vickychijwani.spectre.view.PostListActivity.access$lambda$2(PostListActivity.java)
       at me.vickychijwani.spectre.view.PostListActivity$$Lambda$3.run()
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:135)
       at android.app.ActivityThread.main(ActivityThread.java:5254)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
```

**Comment by vickychijwani** [comment]
This doesn't happen anymore.
